#!/usr/bin/env python3

import sys
import os
import semver
from configparser import ConfigParser

import boto3

config_file = '{}/.aws/ecr'.format(os.getenv("HOME"))
config = ConfigParser()

with open(config_file) as f:
    config.read_file(f)
    f.close()

link = config.get('repository', 'link')

if len(sys.argv) < 2:
    repo_name = input("Repository name: ")

else:
    repo_name = sys.argv[1]

print("Repository: {0}".format(repo_name))

if ':' in repo_name:
    repo_name, tag = repo_name.split(':')

print("Listing all images and tags from '{}'".format(repo_name))

client = boto3.client('ecr')

response = client.list_images(
    registryId='871800672816',
    repositoryName=repo_name,
    filter={
        'tagStatus': 'TAGGED'
    }
)

max_version = None
for image in response['imageIds']:
    tag = image['imageTag']
    if tag == 'latest':
        continue

    if not max_version:
        max_version = tag
    else:
        max_version = semver.max_ver(max_version, tag)

print("{}/{}:{}".format(link, repo_name, max_version))
