#!/usr/bin/env python3

import sys
import os
import semver
from configparser import ConfigParser

import boto3

config_file = '{}/.aws/ecr'.format(os.getenv("HOME"))
config = ConfigParser()

with open(config_file) as f:
    config.read_file(f)
    f.close()

link = config.get('repository', 'link')


if len(sys.argv) < 2:
    repo_name = input("Repository name: ")

else:
    repo_name = sys.argv[1]

print("Repository: {0}".format(repo_name))

if ':' in repo_name:
    repo_name, tag = repo_name.split(':')

print("Listing all images from '{}'".format(repo_name))

client = boto3.client('ecr')

output = ''
next_token = ''

while next_token is not None:
    kwargs = {
        'registryId': os.getenv('AWS_ACCOUNT_ID'),
        'repositoryName': repo_name,
        'filter': {
            'tagStatus': 'TAGGED'
        }
    }

    if next_token:
        kwargs['nextToken'] = next_token

    response = client.list_images(**kwargs)

    if 'nextToken' in response and response['nextToken']:
        next_token = response['nextToken']
    else:
        next_token = None

    for image in response['imageIds']:
        output += "{}/{}:{}\n".format(link, repo_name, image['imageTag'])

print(output)
