#!/usr/bin/env python3

import os
import sys
from configparser import ConfigParser

config_file = '{}/.aws/ecr'.format(os.getenv("HOME"))
config = ConfigParser()

with open(config_file) as f:
    config.read_file(f)
    f.close()

link = config.get('repository', 'link')

if len(sys.argv) < 2:
    repo_name = input("Repository name (<alias>:<tag>): ")

else:
    repo_name = sys.argv[1]

print("Repository: {0}".format(repo_name))

if ':' in repo_name:
    repo_name, tag = repo_name.split(':')
else:
    tag = 'latest'

print("Preparing push to '{0}/{1}:{2}'".format(link, repo_name, tag))
os.system('docker push {0}/{1}:{2}'.format(link, repo_name, tag))
